name: 'Flutter Analyse'

on:
  push:
    branches:
      - main
      - master
      - develop
      - release/*
      - hotfix/*
      - patch/*
  pull_request:
    branches:
      - main
      - master
      - develop
      - release/*
      - hotfix/*
      - patch/*
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  analyze:
    name: Flutter Analyze (Lint Check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Analyze (Fail only on errors)
        run: flutter analyze